language: python
python:
  # We don't actually use the Travis Python, but this keeps it organized.
  - "3.5"
  - "3.6"

install:
  - sudo apt-get update
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  # Grab all dependencies
  # Build dependencies
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION setuptools versioneer -c defaults -c conda-forge
  - source activate test-environment
  # Test suite dependencies
  - conda install coverage pip wheel pytest codecov versioneer -c defaults -c conda-forge
  # Module test dependencies
  - conda install ipython coloredlogs ophyd pcds-devices -c defaults -c conda-forge -c lightsource2-tag -c skywalker-tag
  # Build it!
  - python setup.py install

script:
  - coverage run run_tests.py
  - coverage report -m

after_success:
  - codecov
