version: ~> 1.0

env:
  global:
    - secure: "eE1+WNZb3WjsSlxkf5zDM9PmuVvfFW4rGCF6F2SzVPLXcQP/F27isFmFA8apkbXDp6nr7QTCOItcVccsJ6X+J2UmgrQGw/da/CuTHR5SXN4nOpfBbtuIr3nfy8ubBvZUG55s32eYBPhZo/Z2u9eFQGqQla1agK4E37rm2FymP9y7vmcRAMEhr8w8kOvmCIyDL6uKNQXhUBM7WKk3gOk9UDTtrRFHLP4GR5WcoFZJnAa4Jyc0ttR48rJBuDPgEGL8B7H2YVGT1ttaV0gnM3SMOGnECskRzotZZ3dIISHhnn5kQNJ4BfgDUasHua2rXXQ7BuT6eaGw0nudYFPQ2sUq4iCqV9yoXWtSIHfZ46S+rMeazcZcPl6mQBMjhVBoboWAC7q/AJWuHw+3kR8RUcvLQorgeIMwY7/O8Ri8WCOkccKvNTf5DrHBwrQFmt7+PEh3t/fflUzPQmCgmuWoov6rj5wxb11u4CGVb4mnIJ1Ocq8sZERe+JHMpXokBGQ1jE0qOAG/Og2T7E7yy7MFnjZUJD3j6PfAiVZip3KUAWWG5BQOY7LZ3JhmAp/OVQSRM7jS/HW0VF0P8d5ak39ouZ1Bvzi02bsHbsktbiA6LCo8Wif74gjNV5z7pn8C7x2Ir5nSzw/auva1kOapx96NwNDO+d0+F5qeg4vaH5aOBnq6Kts="

    # enable the usage of versions menu which allow versioning of the docs
    # pages and not only the master branch
    - DOCTR_VERSIONS_MENU="1"
    # Dependency files used to build the documentation (space separated)
    - DOCS_REQUIREMENTS="dev-requirements.txt"
    # Options to be passed to flake8 for package linting. Usually this is just
    # the package name but you can enable other flake8 options via this config
    - PYTHON_LINT_OPTIONS="hutch_python"

    # The name of the conda package
    - CONDA_PACKAGE="hutch-python"
    # The folder containing the conda recipe (meta.yaml)
    - CONDA_RECIPE_FOLDER="conda-recipe"
    # Extra dependencies needed to run the tests which are not included
    # at the recipe and dev-requirements.txt. E.g. PyQt
    - CONDA_EXTRAS="pip pandoc pypandoc"
    # Requirements file with contents for tests dependencies
    - CONDA_REQUIREMENTS="dev-requirements.txt"

    # Extra dependencies needed to run the test with Pip (similar to
    # CONDA_EXTRAS) but for pip
    - PIP_EXTRAS=""

jobs:
  allow_failures:
    # PIP build fails due to some conda-specific assumptions, need to fix
    - name: "Python - PIP"

import:
  - pcdshub/pcds-ci-helpers:travis/shared_configs/setup-env-ui.yml
  - pcdshub/pcds-ci-helpers:travis/shared_configs/standard-python-conda-latest.yml
