# Logging yaml file for the hutch-python

# This logging setup will print all 'info' level messages to the console
# unchanged so it replaces print. In the background there are handlers for each
# of the log levels that saves the messages to separate log files.

version: 1
disable_existing_loggers: false

# Define two formatters, one for the console and one for the the log files. The
# reason for simply printing a message is to replace 'print' with logger.info
# that way it will also get logged to a file.
formatters:
    stream:
        format: "%(message)s"
    file:
        format: "%(asctime)s - %(process)d - %(filename)s:%(lineno)4s - %(funcName)s():    %(levelname)-8s %(message)4s"
        datefmt: '%Y-%m-%d %H:%M:%S'

# There are handlers for the console stream and logging to a file for each of
# the log levels.
handlers:
    console:
        class: logging.StreamHandler
        level: INFO
        formatter: stream
        stream: ext://sys.stdout

    debug:
        class: logging.handlers.RotatingFileHandler
        level: DEBUG
        formatter: file
        maxBytes: 20971520 # 20MB
        backupCount: 10
        mode: a
        delay: 0

    info:
        class: logging.handlers.RotatingFileHandler
        level: INFO
        formatter: file
        maxBytes: 10485760 # 10MB
        backupCount: 10
        mode: a
        delay: 0
        
    warn:
        class: logging.handlers.RotatingFileHandler
        level: WARN
        formatter: file
        maxBytes: 10485760 # 10MB
        backupCount: 10
        mode: a
        delay: 0

    error:
        class: logging.handlers.RotatingFileHandler
        level: ERROR
        formatter: file
        maxBytes: 10485760 # 10MB
        backupCount: 10
        mode: a
        delay: 0

    critical:
        class: logging.handlers.RotatingFileHandler
        level: CRITICAL
        formatter: file
        maxBytes: 10485760 # 10MB
        backupCount: 10
        mode: a
        delay: 0

# Root logger sees all the handlers, the hutch_python logger only has the console
root:
    level: DEBUG
    handlers: [console, info, error, critical, debug, warn]
    propogate: no
    
loggers:
    <hutch_python>:
        level: INFO
        handlers: [console]
        propogate: no
