{% set data = load_setup_py_data() %}

package:
  name: hutch-python
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 1

requirements:
  build:
    - python {{PY_VER}}*,>=3.6
    - setuptools

  run:
    - python {{PY_VER}}*,>=3.6
    - ipython
    - pyyaml
    - coloredlogs
    - pyfiglet
    - happi >=0.5.0
    - pcdsdevices >=0.4.0
    - psdm_qs_cli >=0.2.0

test:
  imports:
    - hutch_python
  commands:
    - hutch-python --help

about:
  home: https://github.com/pcdshub/hutch-python
  license: SLAC Open License
  summary: Launcher and config reader for LCLS interactive IPython sessions
