{% set data = load_setup_py_data() %}

package:
  name: hutch-python
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 1
  noarch: python

requirements:
  build:
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - archapp
    - bluesky >=1.6.0
    - coloredlogs
    - cookiecutter >=1.6.0
    - elog
    - happi >=1.8.0
    - ipython
    - jinja2
    - lightpath >=0.3.0
    - matplotlib
    - nabs >=0.1.0
    - pcdscalc >=v0.2.0
    - pcdsdaq >=2.3.0
    - pcdsdevices >=3.1.0
    - pcdsutils >=0.4.0
    - psdaq-control-minimal >=3.3.19
    - psdm_qs_cli >=0.3.1
    - pyfiglet
    - pyqt >=5
    - pyyaml
    - requests
    - simplejson

test:
  imports:
    - hutch_python
  commands:
    - hutch-python --help
    - epicsarch-qs --help

about:
  home: https://github.com/pcdshub/hutch-python
  license: SLAC Open License
  summary: Launcher and config reader for LCLS interactive IPython sessions
