{% set data = load_setup_py_data() %}

package:
  name: hutch-python
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 1

requirements:
  build:
    - python {{PY_VER}}*,>=3.6
    - setuptools

  run:
    - python {{PY_VER}}*,>=3.6
    - ipython
    - pyyaml
    - coloredlogs
    - pyfiglet
    - happi >=1.1.1
    - pcdsdevices >=0.6.0
    - pcdsdaq >1.2.0
    - psdm_qs_cli >=0.2.0
    - lightpath >=0.3.0
    - elog
    - cookiecutter >=1.6.0
    - matplotlib
    - simplejson
    - requests
    - jinja2

test:
  imports:
    - hutch_python
  commands:
    - hutch-python --help

about:
  home: https://github.com/pcdshub/hutch-python
  license: SLAC Open License
  summary: Launcher and config reader for LCLS interactive IPython sessions
