{% set data = load_setup_py_data() %}

package:
  name: hutch-python
  version : {{ data.get('version') }}

source:
  path: ..

build:
  number: 1
  noarch: python

requirements:
  build:
    - python >=3.6
    - setuptools

  run:
    - python >=3.6
    - archapp >=1.0.2
    - bluesky >=1.8.0
    - coloredlogs >=15.0.0
    - cookiecutter >=1.7.0
    - elog >=1.1.0
    - happi >=1.9.0
    - ipython >=7.26.0
    - jinja2 >=2.11.0
    - lightpath >=0.6.0
    - matplotlib >=3.4.0
    - nabs >=1.3.0
    - pcdscalc >=0.3.0
    - pcdsdaq >=2.3.0
    - pcdsdevices >=4.7.0
    - pcdsutils >=0.6.0
    - psdaq-control-minimal >=3.3.19
    - psdm_qs_cli >=0.3.1
    - pyfiglet >=0.8.0
    - pyqt <5.15.0
    - pyyaml >=5.4.0
    - requests >=2.26.0
    - simplejson >=3.17.0

test:
  imports:
    - hutch_python
  commands:
    - hutch-python --help
    - epicsarch-qs --help

about:
  home: https://github.com/pcdshub/hutch-python
  license: SLAC Open License
  summary: Launcher and config reader for LCLS interactive IPython sessions
