name: PCDS Standard Testing

on:
  push:
  pull_request:
  release:
    types:
      - created

jobs:
  standard:
    uses: pcdshub/pcds-ci-helpers/.github/workflows/python-standard.yml@master
    with:
      # The workflow needs to know the package name.  This can be determined
      # automatically if the repository name is the same as the import name.
      package-name: "hutch-python"
      # Extras that will be installed for both conda/pip:
      testing-extras: ""
      # Extras to be installed only for conda-based testing:
      conda-testing-extras: "ipython=8.4.0 pandoc pypandoc"
      # Extras to be installed only for pip-based testing:
      pip-testing-extras: "ipython==8.4.0 lightpath"
      # Set if using setuptools-scm for the conda-build workflow
      use-setuptools-scm: true
